dictionaries:
  - en
  - en_GB
  - pt

# Files to exclude
excluded_files:
  - "*.v"

# Words to exclude
excluded_words:
  - typoci
  - r'*'
  - r'Hello\nWorld'
  - variadic
  - palavras-chave
  - outras
  - linguagens
  - podem
  - ser
  - usados
  - uma
  - linguagem
  - muito
  - pequena
  - por
  - possui
  - poucas
  - Existem
  - cerca
