dictionaries:
  - en
  - en_GB

# Files to exclude
excluded_files:
  - "*.v"

# Words to exclude
excluded_words:
  - typoci
  - r'*'
  - r'Hello\nWorld'
  - variadic
  - Operadores
  - Esta
  - discute
  - principais
  - condicionais
  - suporta
  - seguintes
  - alterar
  - valores
  - inicializar
  - mundo
  - outras
  - linguagens
  - permite
  - menor
  - maior
  - igual
  - booleanos
  - mesmo
  - especiais
  - opcional
  