dictionaries:
  - de
  - en
  - en_GB
  - pt_BR

# Files to exclude
excluded_files:
  - "*.v"

# Words to exclude
excluded_words:
  - typoci
  - r'*'
  - r'Hello\nWorld'
  - variadic
  - palavras-chave
  - outras
  - linguagens
  - podem
  - ser
  - usados
  - uma
  - linguagem
  - muito
  - pequena
  - por
  - possui
  - poucas
  - Existem
  - cerca
  - Operadores
  - Esta
  - discute
  - principais
  - condicionais
  - suporta
  - seguintes
  - alterar
  - valores
  - inicializar
  - mundo
  - outras
  - linguagens
  - permite
  - menor
  - maior
  - igual
  - booleanos
  - mesmo
  - especiais
  - opcional
  - Operadores
  - Primitivos
  - tem
  - menos
  - tipos
  - pode
  - ser
  - inteiro
  - tipo
  - compostos
  - subclassificado
  - significa
  - positivo
  - negativo
  - apenas
  - Tamanho
